-- Fix relationships for proper GraphQL schema generation
-- This script ensures that posts are linked explicitly to the public profiles table
-- instead of the private auth.users table, allowing pg_graphql to expose the relation.

-- 1. First, make sure all users have a profile (backfill)
INSERT INTO public.profiles (id, display_name, avatar_url)
SELECT 
  id, 
  COALESCE(raw_user_meta_data->>'full_name', raw_user_meta_data->>'name', split_part(email, '@', 1)),
  raw_user_meta_data->>'avatar_url'
FROM auth.users
WHERE id NOT IN (SELECT id FROM public.profiles);

-- 2. Drop the old foreign key constraint pointing to auth.users
-- Note: 'posts_author_id_fkey' is the default name generated by Postgres.
-- If you have a different name, you might need to check information_schema.
ALTER TABLE public.posts
  DROP CONSTRAINT IF EXISTS posts_author_id_fkey;

-- 3. Add the new foreign key constraint pointing to public.profiles
ALTER TABLE public.posts
  ADD CONSTRAINT posts_author_id_fkey
  FOREIGN KEY (author_id)
  REFERENCES public.profiles(id)
  ON DELETE CASCADE;

-- 4. Comment to trigger schema cache reload (optional but good practice)
COMMENT ON TABLE public.posts IS 'Blog posts table with RLS policies and link to profiles';
